# This workflow will run eslint and prettier checks on pull requests to ensure code quality and consistency

name: PR Linter

on:
    pull_request:
        branches:
            - master
    workflow_dispatch:

concurrency:
    group: pr-linter-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: npm
            - name: Install dependencies
              run: npm ci
            - name: Run ESLint
              run: npm run lint
            - name: Run Prettier
              run: npm run format:check
            - name: Fix Prettier errors
              run: npm run format
              if: failure()
            - name: Run typecheck
              run: npm run typecheck
            - name: Run tests
              run: npm run test:run
